version: "3.9"

services:
  server:
    build: server
    ports:
      - "65011:65011"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
    
  worker:
    build: worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - SERVER_URL=http://server:65011

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
